addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "1.21.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "1.3.2")
addSbtPlugin("com.eed3si9n"       % "sbt-assembly"             % "2.3.0")
addSbtPlugin("org.typelevel"      % "sbt-tpolecat"             % "0.5.4")
addSbtPlugin("org.scalameta"      % "sbt-scalafmt"             % "2.5.2")
addSbtPlugin("ch.epfl.scala"      % "sbt-scalafix"             % "0.14.6")
addSbtPlugin("io.spray"           % "sbt-revolver"             % "0.10.0")
